### ISSUE TITLE
Write specification

### ISSUE THREAD

**Issue by mht-dotsource** [commercetools/commercetools-order-message-processor#1]
We need a specification what the service should do.

**Comment by nkuehn** [comment]
sorry guys, time wise I cannot contribute relevant effort but will try what I can. 

What is this implementation supposed to do?  I just know the repo name and that sounds like a bad idea: If it's a generic implementation of a Message listener,  i.e. a reimplementation of https://github.com/sphereio/sphere-message-processing  in Java it should not be order-specific.  

If it's doing a certain thing, e.g. sending emails that should be part of the name.  

BTW: If it's just sending emails I would not re-implement it but rather take the existing "reliably send an order email" implementation at https://github.com/OlegIlyenko/sphere-message-processing-example  and just add the templating call to SUNRISE (which I don't like from an architecture perspective because it creates a runtime dependency of an "independent" backend service to the frontend instance. You can just implement it in SUNRISE directly then.  IMHO it should render the template itself. 

If it's doing something else I can help specifying it but would like to know which of the user stories  ;-)

**Comment by mht-dotsource** [comment]
My understanding is the following: The service should "poll" for specific messages (e.g. OrderCreated) and process them under certain conditions (e.g. there is no attribute on order that states that a confirmation email was send)

After that it calls an endpoint (e.g. in sunrise) that either send the mail for that order or provides an template for the email.

At the moment the task and the naming is just to vague.

**Comment by butenkor** [comment]
@mht-dotsource @nkuehn https://github.com/commercetools/commercetools-order-message-processor/pull/3
